// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: api/dep/dep.proto

package dep

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Num  string `protobuf:"bytes,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *CreateDepRequest) Reset() {
	*x = CreateDepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepRequest) ProtoMessage() {}

func (x *CreateDepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepRequest.ProtoReflect.Descriptor instead.
func (*CreateDepRequest) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDepRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepRequest) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

type CreateDepReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateDepReply) Reset() {
	*x = CreateDepReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDepReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepReply) ProtoMessage() {}

func (x *CreateDepReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepReply.ProtoReflect.Descriptor instead.
func (*CreateDepReply) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDepReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateDepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UpdateDepRequest) Reset() {
	*x = UpdateDepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepRequest) ProtoMessage() {}

func (x *UpdateDepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepRequest) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDepRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDepRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateDepReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateDepReply) Reset() {
	*x = UpdateDepReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDepReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepReply) ProtoMessage() {}

func (x *UpdateDepReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepReply.ProtoReflect.Descriptor instead.
func (*UpdateDepReply) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDepReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDepRequest) Reset() {
	*x = DeleteDepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepRequest) ProtoMessage() {}

func (x *DeleteDepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepRequest) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDepRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDepReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDepReply) Reset() {
	*x = DeleteDepReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDepReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepReply) ProtoMessage() {}

func (x *DeleteDepReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepReply.ProtoReflect.Descriptor instead.
func (*DeleteDepReply) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDepReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDepRequest) Reset() {
	*x = GetDepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepRequest) ProtoMessage() {}

func (x *GetDepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepRequest.ProtoReflect.Descriptor instead.
func (*GetDepRequest) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{6}
}

func (x *GetDepRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDepReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Num  uint32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *GetDepReply) Reset() {
	*x = GetDepReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDepReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepReply) ProtoMessage() {}

func (x *GetDepReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepReply.ProtoReflect.Descriptor instead.
func (*GetDepReply) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepReply) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDepReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDepReply) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Dep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Num  uint32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Dep) Reset() {
	*x = Dep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dep) ProtoMessage() {}

func (x *Dep) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dep.ProtoReflect.Descriptor instead.
func (*Dep) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{8}
}

func (x *Dep) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dep) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ListDepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ListDepRequest) Reset() {
	*x = ListDepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepRequest) ProtoMessage() {}

func (x *ListDepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepRequest.ProtoReflect.Descriptor instead.
func (*ListDepRequest) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{9}
}

func (x *ListDepRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListDepReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dep []*Dep `protobuf:"bytes,1,rep,name=dep,proto3" json:"dep,omitempty"`
}

func (x *ListDepReply) Reset() {
	*x = ListDepReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_dep_dep_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDepReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepReply) ProtoMessage() {}

func (x *ListDepReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_dep_dep_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepReply.ProtoReflect.Descriptor instead.
func (*ListDepReply) Descriptor() ([]byte, []int) {
	return file_api_dep_dep_proto_rawDescGZIP(), []int{10}
}

func (x *ListDepReply) GetDep() []*Dep {
	if x != nil {
		return x.Dep
	}
	return nil
}

var File_api_dep_dep_proto protoreflect.FileDescriptor

var file_api_dep_dep_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x70, 0x2f, 0x64, 0x65, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x22, 0x38, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x20, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x3b,
	0x0a, 0x03, 0x44, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x22, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22,
	0x2e, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1e, 0x0a, 0x03, 0x64, 0x65, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x44, 0x65, 0x70, 0x52, 0x03, 0x64, 0x65, 0x70, 0x32,
	0xc2, 0x02, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x12, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x3f, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x12, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65,
	0x70, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x3f, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64,
	0x65, 0x70, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x36, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x12, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x39, 0x0a, 0x07, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x70, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x1f, 0x0a, 0x07, 0x61, 0x70, 0x69, 0x2e, 0x64, 0x65, 0x70, 0x50,
	0x01, 0x5a, 0x12, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65,
	0x70, 0x3b, 0x64, 0x65, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_dep_dep_proto_rawDescOnce sync.Once
	file_api_dep_dep_proto_rawDescData = file_api_dep_dep_proto_rawDesc
)

func file_api_dep_dep_proto_rawDescGZIP() []byte {
	file_api_dep_dep_proto_rawDescOnce.Do(func() {
		file_api_dep_dep_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_dep_dep_proto_rawDescData)
	})
	return file_api_dep_dep_proto_rawDescData
}

var file_api_dep_dep_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_dep_dep_proto_goTypes = []interface{}{
	(*CreateDepRequest)(nil), // 0: api.dep.CreateDepRequest
	(*CreateDepReply)(nil),   // 1: api.dep.CreateDepReply
	(*UpdateDepRequest)(nil), // 2: api.dep.UpdateDepRequest
	(*UpdateDepReply)(nil),   // 3: api.dep.UpdateDepReply
	(*DeleteDepRequest)(nil), // 4: api.dep.DeleteDepRequest
	(*DeleteDepReply)(nil),   // 5: api.dep.DeleteDepReply
	(*GetDepRequest)(nil),    // 6: api.dep.GetDepRequest
	(*GetDepReply)(nil),      // 7: api.dep.GetDepReply
	(*Dep)(nil),              // 8: api.dep.Dep
	(*ListDepRequest)(nil),   // 9: api.dep.ListDepRequest
	(*ListDepReply)(nil),     // 10: api.dep.ListDepReply
}
var file_api_dep_dep_proto_depIdxs = []int32{
	8,  // 0: api.dep.ListDepReply.dep:type_name -> api.dep.Dep
	0,  // 1: api.dep.DepService.CreateDep:input_type -> api.dep.CreateDepRequest
	2,  // 2: api.dep.DepService.UpdateDep:input_type -> api.dep.UpdateDepRequest
	4,  // 3: api.dep.DepService.DeleteDep:input_type -> api.dep.DeleteDepRequest
	6,  // 4: api.dep.DepService.GetDep:input_type -> api.dep.GetDepRequest
	9,  // 5: api.dep.DepService.ListDep:input_type -> api.dep.ListDepRequest
	1,  // 6: api.dep.DepService.CreateDep:output_type -> api.dep.CreateDepReply
	3,  // 7: api.dep.DepService.UpdateDep:output_type -> api.dep.UpdateDepReply
	5,  // 8: api.dep.DepService.DeleteDep:output_type -> api.dep.DeleteDepReply
	7,  // 9: api.dep.DepService.GetDep:output_type -> api.dep.GetDepReply
	10, // 10: api.dep.DepService.ListDep:output_type -> api.dep.ListDepReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_dep_dep_proto_init() }
func file_api_dep_dep_proto_init() {
	if File_api_dep_dep_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_dep_dep_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDepReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDepReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDepReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDepReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_dep_dep_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDepReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_dep_dep_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_dep_dep_proto_goTypes,
		DependencyIndexes: file_api_dep_dep_proto_depIdxs,
		MessageInfos:      file_api_dep_dep_proto_msgTypes,
	}.Build()
	File_api_dep_dep_proto = out.File
	file_api_dep_dep_proto_rawDesc = nil
	file_api_dep_dep_proto_goTypes = nil
	file_api_dep_dep_proto_depIdxs = nil
}
